version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: shop
    volumes:
      - .:/shop
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - rabbit
      - db
      - redis

  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: .
    command: celery -A core worker -l info
    container_name: celery
    depends_on:
      - rabbit
  redis:
        image: redis:alpine 
        container_name: redis
        ports:
            - "6379:6379"
  db:
    image: postgres:16
    container_name: shopDB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
