version: "3.9"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    container_name: shop
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - rabbit
      - db

  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: .
    command: celery -A core worker -l info
    container_name: celery
    depends_on:
      - rabbit
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

  db:
    image: postgres:16
    container_name: shopDB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  media_volume:

